### ISSUE TITLE
Vanilla parity with displaying slim model skins

### ISSUE THREAD

**Issue by ShareYourHead** [tom5454/CustomPlayerModels#37]
Hi this is just something minor, and I'm probably the only one who cares tbh. In vanilla, the slim model skins are actually displayed differently than they are in the mod. The arms are actually supposed to be displayed half a unit downwards, not in perfect line with the body. I would assume that the pivot point origin remains the same as for standard model skins, but I cannot confirm. Anyway, if this could be adjusted that'd be nice

**Comment by tom5454** [comment]
Yes, but actually no. The vanilla model has a downwards offset (`2.5F` instead of `2.0F`), but it gets thrown away before rendering the player model (inside `BipedModel.setRotationAngles`, the `rotationPointY` gets overwritten based on if the player is sneaking or not.). Here is a screenshot from vanilla: 
![Image: Screenshot](https://user-images.githubusercontent.com/20185760/111210519-a2242600-85cd-11eb-8e0f-c06cc643ec28.png)
