### ISSUE TITLE
[Visual bug] Animations desync upon models reloading

### ISSUE THREAD

**Issue by FluffaMario** [tom5454/CustomPlayerModels#522]
Don't know if this is version specific or not, though been having issues where my friends' animations get reset to their default state every time I need to reload my own model or if they get culled from the view distance.
This ends up being a bit frustrating to deal with manually, since they end up having to reapply everything they changed so I can see them correctly.
Would it be possible to send the current state of each animation on a given model every time it is reloaded so that everything stays synced in these cases?

**Comment by FelisMoon** [comment]
I believe i have seen something like this with held pose animations breaking when relogging or reloading. Seems to be an issue with priority, _and can be fixed by increasing the animation priority of these animations higher than the others._

When reloading models, gestures and toggles seem to sometimes overwrite each other in the wrong order when they share the same priority level.
