### ISSUE TITLE
1.20.4 x Hypixel Incompatibility 

### ISSUE THREAD

**Issue by TrapperMC** [tom5454/CustomPlayerModels#630]
When Using 1.20.4 and Upload to Skin method while running hypixel, You can not actually see your model load other then in your hotbar. I tested 1.8.9 , 1.20, 1.20.1, 1.20.2, 1.19.4, and 1.19.2 with no issues. However 1.20.4 Will not load your model! 

Other Info: Using Curseforge launcher, Only mod loaded was CPM each time, Tried with 2 different models on 1.20.4, 1 of which i tested on the other versions. Forge variant of CPM(Did not test with fabric). The Forge Version is 49.0.31 .

**Comment by Tattleamelia** [comment]
I figured I should chime in rather than making a new post- This issue is happening for me as well, albeit on Fabric 1.20.2 specifically as opposed to Forge 1.20.4.
The strangest thing I've noticed about this bug is that the NPC's that share your skin _do_ use the model, but you yourself cannot.
![image](https://github.com/tom5454/CustomPlayerModels/assets/114160573/683a27a7-daec-40d3-9593-66cf16dc860a)
