### ISSUE TITLE
Unable to change skin, stuck as one skin and won't let me change to another

### ISSUE THREAD

**Issue by kyrapye** [tom5454/CustomPlayerModels#76]
I have been stuck with a "Royal" skin and i'm unable to set it to anything else. I have used the reload function, new skin, mc launcher, edit ect.. I even tried reinstalling and it's still stuck.

Reloading makes me go into the skin I want for 1-2 seconds before reverting to royal again. 
I NEED this fixed ASAP as I need to do lore on my server today.

**Comment by kyrapye** [comment]
I'm using the newest version and same world. I mainly use it for multiplayer though.

**Comment by Xigzagamer** [comment]
Well I just confirmed that this bug not only still exists, but is worse than I thought, my skin is stuck in all of my single player worlds. Even when I'm not using a skin with a custom model. (I thought it was fixed, but I guess it could be fixed in the fabric version which I was using for awhile, but atm I'm using the forge version.)

**Comment by tom5454** [comment]
Check your config file in config/cpm.json, do you have 'selectedModel' field set?

**Comment by Xigzagamer** [comment]
it says ".temp.cpmmodel" based on the name I'm assuming that this is what gets set when you test the model?

**Comment by tom5454** [comment]
Delete the `selectedModel` field from your config. You used an old version that didn't reset the config correctly.
